export enum userTypes {
	LOGIN = 'LOGIN',
	LOGIN_SUCCESS = 'LOGIN_SUCCESS',
	REGISTER = 'REGISTER',
	REGISTER_SUCCESS = 'REGISTER_SUCCESS',
	LOGOUT = 'LOGOUT',
	FETCH_CURRENT_USER = 'FETCH/CURRENT_USER',
	FETCH_CURRENT_USER_SUCCESS = 'FETCH/CURRENT_USER_SUCCESS',
}
