export enum authorsTypes {
	FETCH_AUTHORS = 'AUTHORS/FETCH_AUTHORS',
	FETCH_AUTHORS_SUCCESS = 'AUTHORS/FETCH_AUTHORS_SUCCESS',
	ADD_AUTHOR = 'AUTHORS/ADD_AUTHOR',
	ADD_AUTHOR_SUCCESS = 'AUTHORS/ADD_AUTHOR_SUCCESS',
}
