export enum coursesTypes {
	FETCH_COURSE = 'COURSES/FETCH_COURSE',
	FETCH_COURSE_SUCCESS = 'COURSES/FETCH_COURSE_SUCCESS',
	FETCH_COURSE_ERROR = 'COURSES/FETCH_COURSE_ERROR',
	FETCH_COURSE_BY_ID = 'COURSES/FETCH_COURSE_BY_ID',
	FETCH_COURSE_BY_ID_SUCCESS = 'COURSES/FETCH_COURSE_BY_ID_SUCCESS',
	ADD_COURSE = 'COURSES/ADD_COURSE',
	ADD_COURSE_SUCCESS = 'COURSES/ADD_COURSE_SUCCESS',
	UPDATE_COURSE = 'COURSES/UPDATE_COURSE',
	UPDATE_COURSE_SUCCESS = 'COURSES/UPDATE_COURSE_SUCCESS',
	DELETE_COURSE = 'COURSES/DELETE_COURSE',
	DELETE_COURSE_SUCCESS = 'COURSES/DELETE_COURSE_SUCCESS',
}
